window.webactPortfolioImageMap = {
  "Ace Pet Services": "https://www.webact.com/Resources/images/ace%20pet%20services-1920w.png",
  "Advanced Business Systems": "https://www.webact.com/Resources/images/a-b-s-1920w.png",
  "Aid The Children": "https://www.webact.com/Resources/images/Aid-The-Children-1920w.png",
  "Aces Driving School": "https://www.webact.com/Resources/images/ACES-DRIVING-SCHOOL-1920w.png",
  "Air Techs HVAC": "https://www.webact.com/Resources/images/airTechsHvac-1920w.png",
  "All Concrete Works & Landscaping": "https://www.webact.com/Resources/images/ALL-CONCRETE-WORKS---LANDSCAPING-1920w.png",
  "All Go Transportation": "https://www.webact.com/Resources/images/AllGoTransport-1920w.png",
  "All-Star Pizza": "https://www.webact.com/Resources/images/allStarPizza-1920w.png",
  "Alta Partners": "https://www.webact.com/Resources/images/Alta_Partners-1920w.png",
  "American Sewer": "https://www.webact.com/Resources/images/WebactAmericanSewer-1920w.png",
  "Andree Hudson Art": "https://www.webact.com/Resources/images/Andree_Hudson_Art-1920w.png",
  "Apex Denver Locksmith": "https://www.webact.com/Resources/images/Apex_Denver_Locksmith-1920w.png",
  "Ariana Waterfall": "https://www.webact.com/Resources/images/arianaWaterfall-9f2a1f5e-1920w.png",
  "Aspire Counseling": "https://www.webact.com/Resources/images/AspireCounseling-1920w.png",
  "Aspire Hope For Kids": "https://www.webact.com/Resources/images/Aspire-Hope-For-Kids-1920w.png",
  "Atlee Care": "https://www.webact.com/Resources/images/Atlee-Care-1920w.png",
  "Axel Medical Transportation": "https://www.webact.com/Resources/images/WebactAxelMedicalTransport-1920w.png",
  "AY Home Health Care": "https://www.webact.com/Resources/images/AY-Home-Health-Care-1920w.png",
  "Barbarians Cave Surf": "https://www.webact.com/Resources/images/WebactBarbariansCaveSurf-e6d3047a-1920w.png",
  "Barner Moving": "https://www.webact.com/Resources/images/WebactBarnerMoving-1920w.png",
  "Bayou Solar": "https://www.webact.com/Resources/images/Bayou-Solar-1920w.png",
  "Beltway Home Inspections": "https://www.webact.com/Resources/images/Beltway-Home-Inspections-1920w.png",
  "Benefits Matter": "https://www.webact.com/Resources/images/benefitsMatter-1920w.png",
  "Board Game Republic": "https://www.webact.com/Resources/images/Board-Game-Republic-1920w.png",
  "Brick House Salon": "https://www.webact.com/Resources/images/brickHouseSalon-1920w.png",
  "Bruno Jambor": "https://www.webact.com/Resources/images/Bruno_Jambor-1920w.png",
  "Budget Control Services": "https://www.webact.com/Resources/images/bcs%20collect-1920w.png",
  "Building Better Transit": "https://www.webact.com/Resources/images/Building_Better_Transit-1920w.png",
  "Callahan Hayes": "https://www.webact.com/Resources/images/callahanHayes-1920w.png",
  "Carie's Posing Suits": "https://www.webact.com/Resources/images/cariesPosingSuits-1920w.png",
  "Cass And Company Salon": "https://www.webact.com/Resources/images/cassAndCompany-1920w.png",
  "Century Tire Inc.": "https://www.webact.com/Resources/images/Century_Tire_inc-1920w.png",
  "Chutney Indian Cuisine": "https://www.webact.com/Resources/images/ChutneyIndianCusine-1920w.png"
};
