import fs from"node:fs/promises";import path from"node:path";import*as cheerio from"cheerio";import sharp from"sharp";import{transform}from"lightningcss";import{minify}from"terser";
const root=path.resolve(process.argv[2]),prefix="/webact-redesign/",sizes=[320,640,960,1440],skip=new Set([".git","node_modules","tools"]);
const report={images:0,variants:0,html:0,css:0,js:0,warnings:[]};
async function walk(d){let out=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(skip.has(e.name))continue;let f=path.join(d,e.name);e.isDirectory()?out.push(...await walk(f)):out.push(f)}return out}
async function ok(f){try{await fs.access(f);return true}catch{return false}}
const posix=s=>s.split(path.sep).join("/");
function local(u,h){if(!u||/^(https?:|data:|blob:|#)/i.test(u))return null;u=decodeURI(u.split("?")[0]);if(u.startsWith(prefix))return path.join(root,u.slice(prefix.length));if(u.startsWith("/"))return path.join(root,u.slice(1));return path.resolve(path.dirname(h),u)}
function url(f,o,h){if(o.startsWith(prefix))return prefix+posix(path.relative(root,f));if(o.startsWith("/"))return"/"+posix(path.relative(root,f));return posix(path.relative(path.dirname(h),f))}
function v(f,w,x){let p=path.parse(f);return path.join(p.dir,`${p.name}-${w}.${x}`)}
const files=await walk(root);
for(const f of files.filter(x=>/\.(png|jpe?g)$/i.test(x))){try{let m=await sharp(f).metadata();if(!m.width)continue;let ws=[...new Set([...sizes.filter(x=>x<=m.width),m.width])];for(const w of ws){for(const ext of["webp","avif"]){let dest=v(f,w,ext);if(!await ok(dest)){let q=ext==="webp"?74:50;await sharp(f).rotate().resize({width:w,withoutEnlargement:true})[ext]({quality:q,effort:5}).toFile(dest);report.variants++}}}report.images++}catch(e){report.warnings.push(`image ${f}: ${e.message}`)}}
for(const f of files.filter(x=>x.endsWith(".html")&&!/before-|backup/i.test(path.basename(x)))){try{let raw=await fs.readFile(f,"utf8"),$=cheerio.load(raw,{decodeEntities:false}),hero=null;
if(!$("#wa-critical").length)$("head").prepend(`<style id="wa-critical">html{box-sizing:border-box;-webkit-text-size-adjust:100%}*,*:before,*:after{box-sizing:inherit}body{margin:0}img,picture,svg,video{display:block;max-width:100%;height:auto}.skip-link{position:fixed;z-index:99999;left:1rem;top:1rem;transform:translateY(-200%);padding:.75rem 1rem;background:#071421;color:#fff}.skip-link:focus{transform:none}:focus-visible{outline:3px solid #33abe1;outline-offset:3px}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.01ms!important;animation-iteration-count:1!important;transition-duration:.01ms!important;scroll-behavior:auto!important}}</style>`);
if(!$(".skip-link").length)$("body").prepend('<a class="skip-link" href="#main-content">Skip to main content</a>');let main=$("main").first();if(main.length&&!main.attr("id"))main.attr("id","main-content");
let imgs=$("img").toArray();for(let i=0;i<imgs.length;i++){let im=$(imgs[i]),o=im.attr("src"),src=local(o,f);if(!src||!await ok(src))continue;let m=await sharp(src).metadata();if(!m.width||!m.height)continue;im.attr({width:String(m.width),height:String(m.height),decoding:"async"});let isHero=!hero&&(im.closest('[class*="hero"],[id*="hero"]').length||i===0);isHero?(im.attr({loading:"eager",fetchpriority:"high"}),hero=true):im.attr({loading:"lazy",fetchpriority:"low"});if(!im.attr("alt"))im.attr("alt",path.parse(src).name.replace(/[-_]+/g," "));if(!/\.(png|jpe?g)$/i.test(src))continue;let ws=[...new Set([...sizes.filter(x=>x<=m.width),m.width])],wp=[],av=[];for(const w of ws){let a=v(src,w,"webp"),b=v(src,w,"avif");if(await ok(a))wp.push([w,a]);if(await ok(b))av.push([w,b])}if(!wp.length)continue;let ss=wp.map(([w,x])=>`${url(x,o,f)} ${w}w`).join(", "),as=av.map(([w,x])=>`${url(x,o,f)} ${w}w`).join(", "),sz=im.attr("sizes")||"(max-width:700px) 100vw,(max-width:1200px) 80vw,1440px";im.attr({src:url(wp.at(-1)[1],o,f),srcset:ss,sizes:sz});if(!im.parent().is("picture"))im.wrap("<picture></picture>");let p=im.parent();if(as&&!p.find('source[type="image/avif"]').length)p.prepend(`<source type="image/avif" srcset="${as}" sizes="${sz}">`);if(!p.find('source[type="image/webp"]').length)p.prepend(`<source type="image/webp" srcset="${ss}" sizes="${sz}">`);if(isHero&&!$('link[data-wa-hero]').length)$("head").prepend(`<link rel="preload" as="image" type="image/webp" fetchpriority="high" data-wa-hero href="${url(wp.at(-1)[1],o,f)}" imagesrcset="${ss}" imagesizes="${sz}">`)}
$("script[src]").each((_,e)=>{let s=$(e),src=s.attr("src")||"";if(s.attr("async")!==undefined||s.attr("defer")!==undefined||s.attr("type")==="module")return;/jotfor|jotform/i.test(src)?(s.attr("data-delayed-src",src),s.removeAttr("src")):s.attr("defer","")});
$("iframe[src]").each((_,e)=>{let q=$(e),s=q.attr("src")||"";q.attr("loading","lazy");if(/jotform|youtube|vimeo|maps\.google/i.test(s)){q.attr("data-src",s).removeAttr("src").addClass("js-lazy-third-party")}});
if($(".js-lazy-third-party").length&&!$("#wa-lazy-third-party").length)$("body").append(`<script id="wa-lazy-third-party">(()=>{const l=e=>{if(e.dataset.src&&!e.src){e.src=e.dataset.src;delete e.dataset.src}},f=[...document.querySelectorAll(".js-lazy-third-party[data-src]")];if("IntersectionObserver"in window){const o=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){l(x.target);o.unobserve(x.target)}}),{rootMargin:"400px"});f.forEach(x=>o.observe(x))}else f.forEach(l);const t=()=>document.querySelectorAll("script[data-delayed-src]").forEach(o=>{let s=document.createElement("script");s.src=o.dataset.delayedSrc;s.defer=true;o.replaceWith(s)});["pointerdown","keydown","touchstart"].forEach(n=>addEventListener(n,t,{once:true,passive:true}));addEventListener("load",()=>setTimeout(t,3500),{once:true})})();</script>`);
if(!$('script[data-wa-schema="org"]').length)$("head").append(`<script type="application/ld+json" data-wa-schema="org">${JSON.stringify({"@context":"https://schema.org","@type":["Organization","LocalBusiness"],"name":"WebAct","url":"https://www.webact.com/","email":"support@webact.com","telephone":"+1-855-697-4336","address":{"@type":"PostalAddress","streetAddress":"11479 South Pine Drive","addressLocality":"Parker","addressRegion":"CO","postalCode":"80134","addressCountry":"US"}})}</script>`);
let out=$.html();if(out!==raw){await fs.writeFile(f,out);report.html++}}catch(e){report.warnings.push(`html ${f}: ${e.message}`)}}
for(const f of files.filter(x=>x.endsWith(".css")&&!x.endsWith(".min.css"))){try{let b=await fs.readFile(f),r=transform({filename:f,code:b,minify:true});if(Buffer.compare(b,r.code)){await fs.writeFile(f,r.code);report.css++}}catch(e){report.warnings.push(`css ${f}: ${e.message}`)}}
for(const f of files.filter(x=>{let r=posix(path.relative(root,x));return x.endsWith(".js")&&!x.endsWith(".min.js")&&(r==="script.js"||r.startsWith("assets/js/"))})){try{let s=await fs.readFile(f,"utf8"),r=await minify(s,{compress:{passes:2},mangle:false});if(r.code&&r.code!==s){await fs.writeFile(f,r.code);report.js++}}catch(e){report.warnings.push(`js ${f}: ${e.message}`)}}
await fs.writeFile(path.join(root,"performance-optimization-report.json"),JSON.stringify(report,null,2));console.log(report);